### ISSUE TITLE
Options are not read from input file

### ISSUE THREAD

**Issue by waqasilyas** [TypeFox/xtext-jflex#3]
The [JFlex documentation](http://jflex.de/manual.html#Specifications) says the file structure looks like this:
```
UserCode
%%
Options and declarations
%%
Lexical rules
```

But the JFlexFragment currently has the following code:
```
		val flexConfig = CharStreams.toString(reader).split("%%")
		declarations = flexConfig.head
		rules = flexConfig.get(1)
```

As you can see it puts "user code" in `declarations` and "options and declarations"  in `rules`. And never reads the third token, which actually contains the rules. 

I am new to both Xtext and JFlex, so maybe one of these sections is optional that I don't know about. I can try and fix the issue, but I wanted to confirm what the intended use is first.

**Comment by waqasilyas** [comment]
I have added a pull request: https://github.com/TypeFox/xtext-jflex/pull/8

Here are main changes:

- It fixes the problem where a flex file with more than two sections was causing problems.
- It also removes accessors for data that is read from the given flex file. Because setting these attributes has no effect as they are always read from the file
- Added ability to skip generation of different sections of the generated flex file
- Added ability to skip certain keywords when generating the flex file

**Comment by JanKoehnlein** [comment]
Merged the PR. Sorry for the delay and thanks for the patch
