### ISSUE TITLE
Allow disabling downloading of jflex library

### ISSUE THREAD

**Issue by waqasilyas** [TypeFox/xtext-jflex#5]
I want to ensure that the fragment always uses the jflex library that I package. For confidence of not mistakenly missing my library, and the fragment downloading its own version, I want to be able to disable downloading of the library.

**Comment by waqasilyas** [comment]
Added pull request: https://github.com/TypeFox/xtext-jflex/pull/7

**Comment by JanKoehnlein** [comment]
When https://github.com/TypeFox/xtext-jflex/pull/12 is merged, we use a plain Gradle dependency to get the lib.
